### ISSUE TITLE
problem when adding the same seance of a cine

### ISSUE THREAD

**Issue by linda59** [linda59/cinema_crud#4]
![add_same_seance](https://cloud.githubusercontent.com/assets/24473921/21136196/eac69d2e-c124-11e6-9585-7f0332ffcb31.png)

**Comment by ghost** [comment]
Ce n'est pas un problème dans la BDD?
Car logiquement même si les dates sont identiques il ne devrait pas avoir de soucis.

**Comment by PAFrancioso** [comment]
En fait, si tous les champs sont identiques ça buggue ; on va au moins faire un try/catch qui retourne un message ("Cette séance existe déjà") dans le cas où tous les champs sont identiques.

**Comment by ghost** [comment]
OK

**Comment by Lucas-H2N** [comment]
Normalement On devrait pouvoir avoir 2 fois le meme film a la meme heure le meme jour, par exemple si le cinema le passe dans deux salles différentes en meme temps. J ecrois que le bug vient de la clé primaire.

**Comment by PAFrancioso** [comment]
Oui, c'est ce que je suis en train de regarder ; une clé primaire doit être unique, donc on va tester si elle n'existe pas déjà

**Comment by ghost** [comment]
Vous en êtes ou les gars?

**Comment by Lucas-H2N** [comment]
Up
