### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Riwat** [linda59/cinema_crud#46]
@teambote noob

**Comment by ghost** [comment]
test

**Comment by ghost** [comment]
retest

**Comment by ghost** [comment]
jkdkjhfuki

**Comment by rplantefeve** [comment]
@Riwat @kameleon83 @linda59 @lolov @PAFrancioso @teambote @Dreitsch

**Comment by rplantefeve** [comment]
TESt

**Comment by Riwat** [comment]
@Riwat @kameleon83 @linda59 @lolov @PAFrancioso @teambote @Dreitsch Leave a comment

**Comment by Riwat** [comment]
@Riwat @kameleon83 @linda59 @lolov @PAFrancioso @teambote @Dreitsch test
