### ISSUE TITLE
Finalisation de fonction suppression de film en tant qu admin quand celui ci est déjà programmé

### ISSUE THREAD

**Issue by SebastienHus** [linda59/cinema_crud#7]
Quand nous sommes connecté en tant qu'admin , il faudrait pouvoir supprimer un film de la base de donnée même si celui ci est déjà programmé dans des cinémas  ou dans les préférences d un utilisateur.

Donc en supprimant le film celui ci se supprimera de la base de donnée , se supprimera des cinéma dans lesquelles il est programmé , se supprimera des préférences utilisateurs .

[amélioration]-> quand le film est supprimé alors l utilisateur doit recevoir un message dans un encadré dans le bas de son écran (qui sera fixe) pour lui dire que le film a été supprimé

[amélioration]->Comme le film pourra être supprimé, l'admin devra pouvoir quand il aura cliquer sur l icone suppression choisir entre différente option du pourquoi le film est supprimé (inapproprié , censuré , droit d auteur non respecte .....) ce choix sera complété par un champ de saisie de texte pour complété sont explication si besoin

**Comment by rplantefeve** [comment]
related to #2

**Comment by SebastienHus** [comment]
mais il y a aussi des idées d amélioration pour la suite
